server:
  forward-headers-strategy: framework
  port: 8080          # всередині контейнера
  servlet:
    context-path: /test
    session:
      cookie:
        # нижче ми ще страхуємося від майбутнього "Cookies disabled"
        http-only: true
        secure: false
        same-site: lax

spring:
  datasource:
    url: ${DB_URL}            # ці змінні ми будемо передавати контейнеру через env
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update        # ок, бо це копія бази
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true

vaadin:
  launch-browser: false
  frontend:
    hotdeploy: false

logging:
  level:
    root: INFO
    com.esvar.dekanat: DEBUG
